"""Backwards-compatible re-export shim — import from submodules directly."""

from .client import HelloFreshClient
from .models import (
    HelloFreshAccountData,
    HelloFreshAuthError,
    HelloFreshCapabilities,
    HelloFreshCatalogRecipe,
    HelloFreshDeliveryOption,
    HelloFreshError,
    HelloFreshFavorite,
    HelloFreshFoodProfile,
    HelloFreshFoodProfileOptions,
    HelloFreshMarketItem,
    HelloFreshNotImplementedError,
    HelloFreshOrder,
    HelloFreshProfileCompletion,
    HelloFreshRecipe,
    HelloFreshRecipeCollection,
    HelloFreshRecipeDetail,
    HelloFreshSubscription,
    HelloFreshWeek,
)

__all__ = [
    "HelloFreshAccountData",
    "HelloFreshAuthError",
    "HelloFreshCapabilities",
    "HelloFreshCatalogRecipe",
    "HelloFreshClient",
    "HelloFreshDeliveryOption",
    "HelloFreshError",
    "HelloFreshFavorite",
    "HelloFreshFoodProfile",
    "HelloFreshFoodProfileOptions",
    "HelloFreshMarketItem",
    "HelloFreshNotImplementedError",
    "HelloFreshOrder",
    "HelloFreshProfileCompletion",
    "HelloFreshRecipe",
    "HelloFreshRecipeCollection",
    "HelloFreshRecipeDetail",
    "HelloFreshSubscription",
    "HelloFreshWeek",
]
